name: 'Build (All)'

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      platform_filter:
        description: 'fnmatch filter for job keys (e.g. msvc-*, msvc-gdk-x64, msys2-*)'
        required: false
        default: 'msvc-*'
        type: string
      enable_artifacts:
        description: 'Force artifact upload'
        required: false
        default: false
        type: boolean
      full_trackmem:
        description: 'Enable full trackmem symbol names'
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  controller:
    name: 'Create test plan'
    runs-on: 'ubuntu-latest'
    outputs:
      platforms-level1: ${{ steps.plan.outputs.platforms-level1 }}
      platforms-others: ${{ steps.plan.outputs.platforms-others }}
    steps:
      - uses: actions/setup-python@main
        with:
          python-version: 3.x
      - uses: actions/checkout@main
        with:
          sparse-checkout: '.github/workflows/create-test-plan.py'
      - name: 'Create plan'
        id: plan
        run: |
          # Adding [sdl-ci-filter GLOB] to the commit message will limit the jobs
          # e.g. [sdl-ci-filter msvc-*]
          EOF=$(openssl rand -hex 32)
          cat >/tmp/commit_message.txt <<$EOF
          ${{ github.event.head_commit.message || '' }}
          $EOF

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "[sdl-ci-filter ${{ github.event.inputs.platform_filter || 'msvc-*' }}]" >> /tmp/commit_message.txt
            if [ "${{ github.event.inputs.enable_artifacts || 'false' }}" = "true" ]; then
              echo "[sdl-ci-artifacts]" >> /tmp/commit_message.txt
            fi
            if [ "${{ github.event.inputs.full_trackmem || 'false' }}" = "true" ]; then
              echo "[sdl-ci-full-trackmem-symbol-names]" >> /tmp/commit_message.txt
            fi
          fi

          python .github/workflows/create-test-plan.py \
            --github-variable-prefix platforms \
            --github-ci \
            --verbose \
            ${{ (github.repository_owner != 'libsdl-org' && '--no-artifact') || '' }} \
            --commit-message-file /tmp/commit_message.txt
  level1:
    needs: [controller]
    uses: './.github/workflows/generic.yml'
    with:
      platforms: ${{ needs.controller.outputs.platforms-level1 }}
  level2:
    needs: [controller, level1]
    uses: './.github/workflows/generic.yml'
    with:
      platforms: ${{ needs.controller.outputs.platforms-others }}
